version: 0.2

env:
  variables:
    CI: true

phases:
  pre_build:
    commands:
      - curl -fsSL https://raw.githubusercontent.com/fishbrain/aws-codebuild-extras/master/install -o /tmp/aws-install && . /tmp/aws-install
  build:
    commands:
      - docker build -t app .
      - docker run --env="CI=${CI}" app /bin/sh -c 'npm test'
      - docker run --env "REACT_APP_ENV=${FISHBRAIN_ENVIRONMENT}" --env "CODEBUILD_GIT_BRANCH=${CODEBUILD_GIT_BRANCH}" --env "NPM_TOKEN=${NPM_TOKEN}" app npm run release
