name: CI

on:
  push:
    branches-ignore:
      - main

jobs:
  test:
    runs-on: warp-ubuntu-latest-x64-2x

    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5
      - name: Enable Corepack
        run: corepack enable
      - uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6
        with:
          node-version-file: '.nvmrc'
          cache: 'yarn'
      - name: Install
        run: yarn

      - name: Test configs
        run: yarn test
        env:
          CI: true
