name: CI

on:
  push:
    branches-ignore:
      - main

jobs:
  test:
    runs-on: warp-ubuntu-latest-x64-2x

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: Enable Corepack
        run: corepack enable
      - uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6.5.0
        with:
          node-version-file: '.nvmrc'
          cache: 'yarn'
      - name: Install
        run: yarn

      - name: Test configs
        run: yarn test
        env:
          CI: true
